name: Formatters

on:
  - push
  - pull_request

env:
  FORCE_COLOR: 1

jobs:
  ormolu:
    name: Ormolu (Haskell Formatter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v1
        with:
          extra-args: --ghc-opt -XTypeApplications
